name: cse
channels:
  - conda-forge
  - bioconda
  - r
dependencies:
  - Python=3.6.*
  - drmaa=0.7.9
  - salmon=0.14.0
  - snakemake=5.4.4
  - pandas=0.24.2
  - requests=2.22.0
  - numpy=1.16.4
  - bowtie2=2.3.5
  - samtools=1.9.0
# following: fix some dependencies for gffutils
  - simplejson=3.16.0
  - six=1.12.0
  - pyfaidx=0.5.3
  - pip:
      - git+https://github.com/daler/gffutils@master