name: pplcs
channels:
  - bioconda
  - conda-forge
  - r
dependencies:
  - python=3.5.*
  - pytz
  - numpy
  - scipy
  - scikit-learn
  - numexpr
  - hdf5
  - pandas=0.19.*
  - psutil
  - statsmodels
  - twobitreader=3.1.4
  - ucsc-bigwigtobedgraph
  - pytables
  - sra-tools
  - fastqc=0.11.*
  - cutadapt=1.12
  - khmer=2.0
  - salmon=0.8.2
  - trim-galore=0.4.1
  - bowtie2
  - samtools
  - deeptools
  - openssl>=1.0.2k
  - boost
  - r-base>=3.1.*
  - r-snow
  - r-snowfall
  - r-bitops
  - r-catools
  - bioconductor-biocinstaller
  - bioconductor-rsamtools
  # LOLA
  # source("http://bioconductor.org/biocLite.R")
  # biocLite("LOLA")