name: pplcs
channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.5.*
  - pytz
  - numpy=1.11.*
  - scipy=0.18.*
  - scikit-learn=0.18.*
  - numexpr=2.6.*
  - hdf5
  - pandas=0.19.*
  - psutil=4.3.*
  - statsmodels=0.6.*
  - twobitreader=3.1.4
  - ucsc-bigwigtobedgraph
  - pytables=3.2.*
  - sra-tools=2.7.*
  - fastqc=0.11.*
  - cutadapt=1.12
  - khmer=2.0
  - salmon=0.8.2
  - trim-galore=0.4.1
