name: pplcs
channels:
  - bioconda
  - conda-forge
  - r
dependencies:
  - python=3.5.*
  - curl
  - conda-forge::readline
  - pytz
  - pysam=0.12.0.1
  - htslib=1.6.*
  - numpy=1.12.1
  - scipy=0.19.1
  - scikit-learn=0.18.1
  - numexpr
  - hdf5
  - pandas=0.19.*
  - psutil
  - statsmodels
  - twobitreader=3.1.4
  - ucsc-bigwigtobedgraph
  - pytables=3.4.2
  - sra-tools
  - fastqc=0.11.*
  - cutadapt=1.12
  - khmer=2.1.2
  - salmon=0.8.2
  - trim-galore=0.4.1
  - bowtie2=2.3.3.1
  - samtools=1.6
  - deeptools=2.5.3
  - openssl>=1.0.2k
  - boost
  - r-base=3.3.*
  - r-openssl
  - r-curl
  - r-devtools
  - r-data.table
  - r-optparse
  - r-reshape2
  - bioconductor-biostrings
  - bioconductor-genomicranges=1.26.*
  - bioconductor-iranges
  - bioconductor-biocinstaller
  - bioconductor-qvalue
  # LOLA
  # source("http://bioconductor.org/biocLite.R")
  # biocLite("LOLA")
  #
  # simpleCache
  # options(unzip = 'internal')
  # require(devtools)
  # install_github("databio/simpleCache", ref="dev")