name: pplcs
channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.5.*
  - pytz
  - numpy
  - scipy
  - scikit-learn
  - numexpr
  - hdf5
  - pandas
  - psutil
  - statsmodels
  - twobitreader=3.1.4
  - ucsc-bigwigtobedgraph
  - pytables
  - sra-tools
  - fastqc=0.11.*
  - cutadapt=1.12
  - khmer=2.0
  - salmon=0.8.2
  - trim-galore=0.4.1
  - bowtie2
  - samtools
  - deeptools
  - openssl>=1.0.2k
